// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("sakuracloud")
	ScopeName = "github.com/sacloud/opentelemetry-collector-sakuracloud/receiver/sakuracloudreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
